# ---------- Base Stage ----------
FROM node:22-alpine AS base
WORKDIR /app
COPY ./backend/package*.json ./

# ---------- Development Stage ----------
FROM base AS dev
RUN yarn install
COPY ./backend .
EXPOSE 3001
CMD ["yarn", "start:dev"]

# ---------- Production Stage ----------
FROM base AS prod
ENV NODE_ENV=production
RUN yarn install
COPY ./backend .
RUN yarn build
EXPOSE 3001
CMD ["yarn", "start"]

