name: Project CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    NODE_VERSION: 20
    WORKDIR: frontend

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: ./.github/actions/setup
                with:
                    node-version: ${{ env.NODE_VERSION }}
                    dir: ${{ env.WORKDIR }}

    lint:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            -   uses: actions/checkout@v3
            -   uses: ./.github/actions/lint
                with:
                    node-version: ${{ env.NODE_VERSION }}
                    dir: ${{ env.WORKDIR }}

    build:
        runs-on: ubuntu-latest
        needs: [setup, lint]
        steps:
            -   uses: actions/checkout@v3
            -   uses: ./.github/actions/build
                with:
                    node-version: ${{ env.NODE_VERSION }}
                    dir: ${{ env.WORKDIR }}