name: Project CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    NODE_VERSION: 20
    WORKDIR: frontend

jobs:
    Setup Project:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: ./.github/actions/setup
                with:
                    node-version: ${{ env.NODE_VERSION }}
                    dir: ${{ env.WORKDIR }}

    Check Lint:
        runs-on: ubuntu-latest
        needs: Setup Project
        steps:
            -   uses: actions/checkout@v3
            -   uses: ./.github/actions/lint
                with:
                    node-version: ${{ env.NODE_VERSION }}
                    dir: ${{ env.WORKDIR }}

    Build Project:
        runs-on: ubuntu-latest
        needs: [Setup Project, Check Lint]
        steps:
            -   uses: actions/checkout@v3
            -   uses: ./.github/actions/build
                with:
                    node-version: ${{ env.NODE_VERSION }}
                    dir: ${{ env.WORKDIR }}